### PR TITLE
Bugsnag opt out

### LINKED ISSUE #1491: Bugsnag still connects even if analytics are disabled
**Describe the bug**
I noticed that the app connects to Bugsnag even with analytics disabled. Care to explain that?

**To Reproduce**
Steps to reproduce the behaviour:
1. Run Frost
2. Sniff phone traffic from another device

**Details (please provide at least the app version):**
 - App Version: 2.3.1 F-Droid

### PR DESCRIPTION
**Pull request by AllanWang**
Resolves #1491

### CODE REVIEW

File: app/src/main/kotlin/com/pitchedapps/frost/utils/Prefs.kt [hunk 1]
```diff
@@ -153,7 +157,15 @@ object Prefs : KPref() {
 
     var verboseLogging: Boolean by kpref("verbose_logging", false)
 
-    var analytics: Boolean by kpref("analytics", true)
+    var analytics: Boolean by kpref("analytics", false) {
+        if (!BuildConfig.DEBUG) {
+            if (it) {
+                Bugsnag.enableExceptionHandler()
+            } else {
+                Bugsnag.disableExceptionHandler()
```
Comment (adolfintel) [inline app/src/main/kotlin/com/pitchedapps/frost/utils/Prefs.kt]: I just checked on my phone, disabling the exception handler isn't enough to disable bugsnag unfortunately (the connection is still open), a restart is required (or just inform the user that the preference will be applied next time the application is started)

Comment (AllanWang) [reply app/src/main/kotlin/com/pitchedapps/frost/utils/Prefs.kt]: I will send bugsnag an email later. It may be that I also have to disable stage notifications, which is probably what it sends at first

Comment (adolfintel) [reply app/src/main/kotlin/com/pitchedapps/frost/utils/Prefs.kt]: Updates on this? Do they have a way to disable bugsnag after initialization?

Comment (AllanWang) [reply app/src/main/kotlin/com/pitchedapps/frost/utils/Prefs.kt]: The initial report is sent on init, so they basically said to late init it. I might end up requiring an app restart since I don't like the idea of init on activity. It also depends on if bugsnag crashes if I fail to init, which I will have to test on my own later

Comment (adolfintel) [reply app/src/main/kotlin/com/pitchedapps/frost/utils/Prefs.kt]: Nothing wrong with requiring an app restart in my opinion. It's not the most elegant solution, but with lack of a better option, I'd do it

Comment (AllanWang) [reply app/src/main/kotlin/com/pitchedapps/frost/utils/Prefs.kt]: They've provided a better solution today. I will work on it tomorrow

Comment (AllanWang) [reply app/src/main/kotlin/com/pitchedapps/frost/utils/Prefs.kt]: If you want you can try this out. I'm reasonably happy with the solution, and given that everything is behind the analytics flag there shouldn't be anything unexpected

Comment (adolfintel) [reply app/src/main/kotlin/com/pitchedapps/frost/utils/Prefs.kt]: Are you still calling initBugsnag before the consent screen? Because that's when it sends an initial batch of data about the device and leaves the connection open for breadcrumbs and crash reports.

**Comment by adolfintel** [comment]
You should change the color of the switch to toggle analytics, it's white on white. (And maybe add a link to bugsnag's privacy policy for completeness)

Other than that, it's good.

image
